version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - LOCALE=en
      - APP_ENV=dev
    volumes:
      - .:/srv/symfony:rw
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - 80
    volumes:
      # Comment out the next line in production
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/symfony/public:ro
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - 8081
    #command: "npm start"