version: '3'

services:
  app:
    image: malulu/php-7.1:latest
    env_file:
     - ../env/global.env
     - ../env/gogo.global.env
    environment:
      - DATABASE_URL=mysql://gogo:gogo@db:3306/gogo
      - HOSTNAME_OUTER_HOST=gogo.test
      - LOCALE=en
    volumes:
      - .:/srv/symfony:rw
    networks:
      - private
  web:
    environment: 
      - VIRTUAL_HOST=gogo.test
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/srv/symfony/public:ro
    networks:
      - private
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - private

networks:
  private:
    driver: bridge
