version: '3'

services:
  app:
    image: malulu/php-7.1:latest
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - LOCALE=en
    volumes:
      - .:/srv/symfony:rw
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - 80
    volumes:
      - ./public:/srv/symfony/public:ro
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
