version: '3'

services:
  app:
    image: malulu/php-7.1:latest
    env_file:
     - .env
    environment:
      - APP_ENV=dev
      - HOSTNAME_OUTER_HOST=gogo.test
      - LOCALE=en
      - DATABASE_URL=mysql://${DB_USER}:${DB_PW}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - .:/srv/symfony:rw
    networks:
      - private
  web:
    build:
      context: ./build/docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/srv/symfony/public:ro
    networks:
      - private
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - private
  db:
    # just a dummy image that get replace by a mysql image if the db composer file is included
    image: alpine:3.7
    networks:
      - private

networks:
  private:
    driver: bridge
