version: '3'

services:
  app:
    image: malulu/php-7.1:latest
    environment:
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      # uncomment for mysql
      # - DATABASE_URL=mysql://gogo:gogo@db:3306/gogo
      - LOCALE=en
    volumes:
      - .:/srv/symfony:rw
    # uncomment for mysql
    #links:
      #- db
    networks:
      - back
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - 80
    volumes:
      - ./public:/srv/symfony/public:ro
    networks:
      - reverse-proxy
      - back
    environment:
      - VIRTUAL_HOST=gogo-staging.*
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      - back

# uncomment for mySql
#  db:
#    image: mysql
#    restart: always
#    expose:
#      - 3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=gogo
#      - MYSQL_DATABASE=gogo
#      - MYSQL_PASSWORD=gogo
#      - MYSQL_USER=gogo
#    networks:
#      - back

networks:
  reverse-proxy:
    external:
      name: reverseproxy_default
  back:
    driver: bridge
