version: '3'

services:
  web:
    ports:
        - 80
  db:
    image: mysql
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=gogo
      - MYSQL_DATABASE=gogo
      - MYSQL_PASSWORD=gogo
      - MYSQL_USER=gogo
    networks:
      - private 