# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool'


#swiftmailer:
    #url: '%env(MAILER_URL)%'
    #spool: { type: 'memory' }